### PR TITLE
Temporarily remove new proposal button

### PR DESCRIPTION
**Pull request by alphastorm**
Per @milkyklim's suggestion:

ygov-finance

### CODE REVIEW

**Comment by antonnell** [comment]
Yo, so why are we removing the button? Why was it suggested?

**Comment by milkyklim** [comment]
Problem is people bashing the button without actual YIP on forum. This is why we end up with on-chain proposals without actual text\idea behind them. 

I would like to hide the button (at least for now) before better idiot-proof solution is there. 

cc @alphastorm

**Comment by alphastorm** [comment]
I think this is probably fine until AC can roll out the new governance stuff, since we don't want people submitting additional proposals until that's live.

Longer term we might want to consider updating the [Proposal How-To](https://gov.yearn.finance/t/proposal-how-to/106) to include YIPs and maybe adding a popup confirmation modal linked to that instead?  That way people will have to confirm they followed the instructions before submitting anything on-chain.  What do you think @antonnell and @milkyklim?

**Comment by milkyklim** [comment]
@alphastorm should we close this one since people need 1 YFI to submit a proposal now?

cc @antonnell

**Pull request closed without merging**
